// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("b8e9af2f-3f39-41bc-9ac1-229857af2e5f")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("ConversationModel.Tests")]
